### ISSUE TITLE
Test Ledger usage in tests

### ISSUE THREAD

**Issue by AlexTheWizardL** [macxred/cashctrl_ledger#19]
### Update: Use Test Ledger for Test Data

Currently, our test data sets are hardcoded within the tests themselves. To improve consistency and maintainability, we propose using the Test Ledger as the source of testing data across all tests.

**Changes:**
- Replace hardcoded test data with data from the Test Ledger.
- Ensure all tests are updated to fetch data from the Test Ledger.

This update will streamline our testing process and ensure a single source of truth for test data.

**Comment by lasuk** [comment]
In order to  use the `TestLedger` class for testing account mirroring, we need to introduce a 'group' column in TestLedger 's account chart. We can derive the group information from comments in the csv account chart.

During our call yesterday, we created an example of such a group column. @AlexTheWizardL: If I recall right, we've created the example on your notebook. Please share it here if you still have the snippet.

**Comment by lasuk** [comment]
Switching tests to TestLedger data will be easier once the automated addition of missing groups in is implemented. 
I thus propose to implement #18 before tackling this issue.

**Comment by AlexTheWizardL** [comment]
We now use Base tests approach that implements the idea of this issue
